# Do not forget to check .env file
version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_EXPOSED_PORT}:6379"
    volumes:
      - ./redis-data:/data

  api:
    depends_on:
      - "redis"
    image: "p0w3r/mt_user_study_api:latest"
    environment:
      - "REDIS_HOST=${REDIS_HOST}"
      - "REDIS_PORT=${REDIS_PORT}"
      - "REDIS_EVAL_SAMPLE_DB_IDX=${REDIS_EVAL_SAMPLE_DB_IDX}"
      - "REDIS_MRANK_DB_IDX=${REDIS_MRANK_DB_IDX}"
      - "REDIS_RESULT_DB_IDX=${REDIS_RESULT_DB_IDX}"
      - "REDIS_STATE_DB_IDX=${REDIS_STATE_DB_IDX}"
      - "REDIS_AUTH_DB_IDX=${REDIS_AUTH_DB_IDX}"
      - "REDIS_MTURK_DB_IDX=${REDIS_MTURK_DB_IDX}"

      - "IMG_SRV_HOST=${IMG_SRV_HOST}"
      - "IMG_SRV_PORT=${IMG_SRV_PORT}"
      - "IMG_SRV_CTX_PTH=${IMG_SRV_CTX_PTH}"
      - "IMG_SRV_REL_URL=${IMG_SRV_REL_URL}"

      - "AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      - "AWS_SECRET=${AWS_SECRET}"
      - "MTURK_SANDBOX=${MTURK_SANDBOX}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "ADMIN_ID=${ADMIN_ID}"
      - "ADMIN_PWD=${ADMIN_PWD}"

      - "GU_GRACEFUL_TIMEOUT=${GU_GRACEFUL_TIMEOUT}"
      - "GU_TIMEOUT=${GU_TIMEOUT}"
      - "GU_KEEP_ALIVE=${GU_KEEP_ALIVE}"
      - "GU_LOG_LEVEL=${GU_LOG_LEVEL}"
      - "GU_MAX_WORKERS=${GU_MAX_WORKERS}"
    ports:
      - "${API_EXPOSED_PORT}:80"
    volumes:
      - ./api/logs:/app/logs
      - ./api/config:/app/config
      - ${DATA_ROOT}:/app/data

  app:
    depends_on:
      - "api"
    image: "p0w3r/mt_user_study_app:latest"
    environment:
      - "APP_MIN_NUM_RANKS=${APP_MIN_NUM_RANKS}"
      - "APP_DEPLOY=${APP_DEPLOY}"
      - "APP_CTX_PTH=${APP_CTX_PTH}"
      - "API_HOST=${API_HOST}"
      - "API_PORT=${API_PORT}"
      - "MTURK_SANDBOX=${MTURK_SANDBOX}"
    ports:
      - "${APP_EXPOSED_PORT}:3000"

  img_srv:
    image: sebp/lighttpd
    volumes:
      - "${IMG_SRV_ROOT}:/var/www/localhost/htdocs"
    ports:
      - "${IMG_SRV_EXPOSED_PORT}:80"
    tty: true
