port: 8081

logging:
  level: DEBUG
  rotation: 500 # MB

study:
  samples:
    num_top_k_imgs: 10
    num_random_imgs: 14
    in_prog_ttl: 60 # in seconds
  init:
    data_root: ${env:DATA_ROOT, data}
    flush: true
    num_samples: 10 # negative number is maximum

backend:
  redis:
    host: ${env:REDIS_HOST, localhost}
    port: ${env:REDIS_PORT, 6379}
    eval_sample_db_idx: ${env:REDIS_EVAL_SAMPLE_DB_IDX, 3}
    m_rank_db_idx: ${env:REDIS_M_RANK_DB_IDX, 4}
    result_db_idx: ${env:REDIS_RESULT_DB_IDX, 5}
    progress_db_idx: ${env:REDIS_STATE_DB_IDX, 6}

image_server:
  https: false
  host: ${env:IMG_SRV_HOST, localhost}
  port: ${env:IMG_SRV_PORT, 8082}
  relative_url: ${env:IMG_SRV_REL_URL, 1}
  img_root: ${env:IMG_SRV_ROOT, data/images}
  img_prefix: wikicaps_
  img_suffix: .png
  context_path: ${env:IMG_CTX_PTH, /}
