port: 8081

logging:
  level: INFO
  rotation: 500 # MB

study:
  samples:
    num_top_k_imgs: 10
    num_random_imgs: 14
    in_prog_ttl: 30 # in seconds
  init:
    data_root: ${env:REDIS_HOST, data}
    flush: true
    num_samples: 10 # negative number is maximum

backend:
  redis:
    host: ${env:REDIS_HOST, localhost}
    port: ${env:REDIS_PORT, 6379}
    eval_sample_db_idx: ${env:REDIS_EVAL_SAMPLE_DB_IDX, 3}
    gt_sample_db_idx: ${env:REDIS_GT_SAMPLE_DB_IDX, 4}
    result_db_idx: ${env:REDIS_RESULT_DB_IDX, 5}
    progress_db_idx: ${env:REDIS_PROGRESS_DB_IDX, 6}

image_server:
  lighttp:
    https: false
    host: localhost
    port: 8082
    context_path: /
    datasources:
      - test: /text_imgs/
