port: 8081

logging:
  level: DEBUG
  rotation: 500 # MB

study:
  samples:
    num_top_k_imgs: 10
    num_random_imgs: 14
    in_prog_ttl: 300 # in seconds
  init:
    data_root: ${env:DATA_ROOT, data}
    flush: true
    num_samples: 1000 # negative number is maximum

backend:
  redis:
    host: ${env:REDIS_HOST, localhost}
    port: ${env:REDIS_PORT, 6379}
    eval_sample_db_idx: ${env:REDIS_EVAL_SAMPLE_DB_IDX, 3}
    m_rank_db_idx: ${env:REDIS_M_RANK_DB_IDX, 4}
    result_db_idx: ${env:REDIS_RESULT_DB_IDX, 5}
    progress_db_idx: ${env:REDIS_STATE_DB_IDX, 6}
    auth_db_idx: ${env:REDIS_AUTH_DB_IDX, 7}
  mturk:
    sandbox: True
    aws_access_key: ${env:AWS_ACCESS_KEY}
    aws_secret: ${env:AWS_SECRET}
    aws_region_name: ${env:AWS_REGION_NAME, us-east-1}
    hit_auto_approval_delay_in_seconds: 21600 # 21600 = 6 hours
    hit_assignment_duration_in_seconds: 300 # 5 min
    hit_reward_live: 0.2
    hit_reward_sandbox: 0.0
    hit_title: Image ranking according to a caption
    hit_description: This survey's goal is to evaluate the ranking of an AI by letting you re-rank images according to captions.
    hit_keywords: image, ranking, AI, visual
    hit_max_assignments: 3
    hit_lifetime: 604800 # 604800 = 1 week's seconds
    worker_quali_req_min_hits_approved: 100
    worker_quali_req_min_percent_approved: 90
    external_question_base_url: ${env:EQ_BASE_URL, https://ltdemos.informatik.uni-hamburg.de/imagerank/study/}
  auth:
    jwt_secret: ${env:JWT_SECRET, }
    jwt_algo: ${env:JWT_ALGO, HS256}
    jwt_ttl: ${env:JWT_TTL, 300}
    admin_id: ${env:ADMIN_ID, admin}
    admin_pwd: ${env:ADMIN_PWD}

image_server:
  https: true
  host: ${env:IMG_SRV_HOST, localhost}
  port: ${env:IMG_SRV_PORT, 8082}
  relative_url: ${env:IMG_SRV_REL_URL, 0}
  context_path: ${env:IMG_SRV_CTX_PTH, /}
  img_root: ${env:IMG_SRV_ROOT, data/images}
  img_prefix: wikicaps_
  img_thumbnail_infix: _thumbnail
  img_suffix: .webp
