# Make sure to config .env file or set env variables correctly!
img_srv:
  image: sebp/lighttpd
  volumes:
    - "${IMG_SRV_ROOT}:/var/www/localhost/htdocs"
  ports:
    - "${IMG_SRV_PORT}:80"
  tty: true
